//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKRIPSI_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_equipment
    {
        public int equipment_id { get; set; }
        public string tag_no { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> manufacture { get; set; }
        public string capacity { get; set; }
        public string fla { get; set; }
        public string rpm { get; set; }
        public string volt { get; set; }
        public string frame { get; set; }
        public Nullable<int> bearing_de { get; set; }
        public Nullable<int> bearing_nde { get; set; }
        public string wiring_diameter { get; set; }
        public string schedule_service { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    
        public virtual m_area m_area { get; set; }
        public virtual m_manufacture m_manufacture { get; set; }
    }
}
