//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKRIPSI_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_material
    {
        public int material_id { get; set; }
        public string material_type { get; set; }
        public string material_ing { get; set; }
        public string material_value { get; set; }
        public string status { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
