//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKRIPSI_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Equipment
    {
        public int m_equip_id { get; set; }
        public string m_tag_no { get; set; }
        public Nullable<int> m_area { get; set; }
        public Nullable<int> m_manufacture { get; set; }
        public Nullable<int> m_capacity { get; set; }
        public string m_fla { get; set; }
        public string m_rpm { get; set; }
        public string m_volt { get; set; }
        public string m_frame { get; set; }
        public Nullable<int> m_bearing_de { get; set; }
        public Nullable<int> m_bearing_nde { get; set; }
        public Nullable<int> m_wiring_de { get; set; }
        public Nullable<int> m_wiring_nde { get; set; }
        public string status { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string m_manu_name { get; set; }
        public string m_area_name { get; set; }
    }
}
