//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKRIPSI_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Equipments
    {
        public int equipment_id { get; set; }
        public string tag_no { get; set; }
        public Nullable<int> area_id { get; set; }
        public Nullable<int> manufacture_id { get; set; }
        public string capacity { get; set; }
        public string fla { get; set; }
        public string rpm { get; set; }
        public string volt { get; set; }
        public string frame { get; set; }
        public Nullable<int> bearing_de { get; set; }
        public Nullable<int> bearing_nde { get; set; }
        public string wiring_diameter { get; set; }
        public string schedule_service { get; set; }
        public string area_name { get; set; }
        public string manufacture_name { get; set; }
        public string de { get; set; }
        public string nde { get; set; }
        public string val_tag_no { get; set; }
        public string wiring_value { get; set; }
        public string last_service { get; set; }
        public string mttf { get; set; }
        public string mttr { get; set; }
        public string overdue { get; set; }
        public string created_date { get; set; }
    }
}
